[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "us_lib"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = []

[tool.setuptools.packages.find]
include = ["us_lib*"]